const Dapps = () => {
    return ( 
        <main className="mt-24 text-[#242426]">
            <div className="flex flex-col gap-y-5">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Wallet Address, Private Key, and Backup Capabilities</p>
                <p>An encrypted backup of certain information associated with your wallet can be stored on eligible devices. The private key is associated with the wallet address and, together, they can be used to authorize the transfer of Digital Assets to and from that wallet address. You are solely responsible for the retention and security of your private key and any mnemonic phrase (“Secret Phrase”) associated with your wallet. You must keep your wallet address, Secret Phrase, and private key access information secure. It is very important that you backup your private keys, backup phrases or passwords. Failure to do so may result in the loss of control of Digital Assets associated with your wallet. You acknowledge and agree that we do not receive or store your wallet password, encrypted private key, unencrypted private key, or Secret Phrase associated with your wallet. We cannot generate a new password for your wallet if you fail to remember your original password. If you have not safely stored a backup of any wallet address and private key pairs maintained in your wallet, you accept and acknowledge that any Digital Assets you have associated with such wallet address will become inaccessible. Accordingly, we shall have no responsibility or liability whatsoever in the event you are unable to access your wallet for any reason including without limitation your failure to keep your wallet address, Secret Phrase and private key information secure.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Use of DApps and DEX</p>
                <p>If you access or use DApps or DEX, including, without limitation, DApp functionality embedded within the Services such as the Trade/Swap Digital Assets function, you acknowledge and agree that: (i) wealthassets is not responsible for your access or use of DApps or DEX and shall have no liability whatsoever in connection with your use of DApps or DEX, including, without limitation, any transactions you dispute; (ii) the limits of amounts that you may exchange via DEX per day shall be subject to any requirements of the third-party developed Smart Contracts; (iii) blockchain operations are irrevocable meaning when you conduct any transactions via DApps or DEX, you shall be solely responsible for the consequences of any issues associated with such transactions, including, without limitation, your transfer to an incorrect address or problems associated with the node servers selected by you; (iv) when you use DApps or DEX, third-party developed Smart Contracts may charge you handling fees and/or service fees and any information displayed on wealthassets relating to such fees are for your reference only as wealthassets cannot and does not guarantee its accuracy, applicability, reliability, integrity or appropriateness, nor shall wealthassets be liable for any loss or damage that may be caused directly or indirectly by your use of these contents; and (v) Wealth Assets does not currently charge any service fees or handling fees for the use of DApps or DEX, however, wealthassets may, in its discretion, charge such fees at any time in the future. Any updated fees will apply to any transaction that occurs following the effective date of the updated fees.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Use of Staking Service</p> 
                <p>If you access or use the Staking Service, a third party may stake certain Digital Assets on your behalf (“Staked Digital Assets”), acting as a transaction validator on the applicable blockchain network. If a block of transactions is successfully validated using such Staked Digital Assets, a reward is granted by that network (“Staking Reward”). You acknowledge and agree that wealthassets is not responsible for: (i) your use of the Staking Service and shall have no liability whatsoever in connection with your use of the Staking Service; (ii) ensuring Staking will occur on a continuous basis; and (iii) ensuring any particular Digital Asset will be staked or will continue to be staked.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Buy Digital Assets with Supported Credit or Debit Cards</p> 
                <p>If you use wealthassets to purchase Digital Assets with your credit or debit card, a third party will convert your chosen amount into the applicable Digital Asset and credit it to your wallet. You acknowledge and agree that: (i) wealthassets is not responsible for your use of such third party service and shall have no liability whatsoever in connection with your use of such service; (ii) you will be subject to any terms and conditions imposed by the relevant third party service provider; (iii) wealthassets has no ability to change, withdraw or cancel any conversion requests you place; (iv) wealthassets is not responsible for any exchange rates offered by the relevant third party service provider(s); and (v) wealthassets is not responsible for any fees charged by the relevant third party service provider(s) or your bank or credit card issuer(s).</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Digital Asset Transactions</p> 
                <p>In order for all proposed Digital Asset transactions to be completed, they must be confirmed and recorded in the Digital Asset’s associated public blockchain. Such networks are decentralized, peer-to-peer networks supported by independent third parties, which we do not own, control, or operate. We have no control over the blockchain networks and, therefore, cannot and do not ensure that any transaction details that you submit via our Services will be confirmed and processed. By using wealthassets, you acknowledge and agree that: (i) we do not have the ability to cancel or otherwise modify your transaction; (ii) the transaction details you submit may not be completed, or may be substantially delayed, by the applicable blockchain networks; (iii) we do not store, send, or receive Digital Assets; and (iv) any transfer that occurs in relation to any Digital Asset occurs on the relevant blockchain network and not on a network owned by us and therefore we do not guarantee the transfer of title or right in any Digital Asset.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold">Accuracy of Information Provided by User</p>
                <p>You represent and warrant that any information you provide via the Services is accurate and complete. You accept and acknowledge that we are not responsible for any errors or omissions that you make in connection with any Digital Asset transaction initiated via the Services. We strongly encourage you to review your transaction details carefully before attempting to transfer a Digital Asset.</p>
            </div>
        </main>
     );
}
 
export default Dapps;