const WalletRegistration = () => {
    return ( 
        <main className="mt-24 text-[#242426]">
            <div className="flex flex-col gap-y-5">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Wallet Registration and Security</p>
                <p>You must either import or create a wallet in order to use Wealth Assets. When you create a wallet, you will be assigned a private key. You agree to immediately notify us of any unauthorized use of your private key or any other breach of security of your wallet. Notwithstanding the foregoing, you acknowledge and agree that you shall assume all risks related to the use of the Services and you shall be solely responsible for maintaining the confidentiality and security of your private key. When you create a wallet, you are strongly advised to take precautions in order to avoid loss of access to and/or control over your wallet. Suggested measures include, but are not limited to, the following: (a) creating a strong unique password that you do not use for any other purpose (i.e. different to your phone password or any other passwords you use for websites, online services, etc.) and leveraging biometric authentication if available; (b) do not store the private key and Secret Phrase in plain text online or in an unsecured physical location; (c) limiting access to your devices and your wallet; (d) taking all necessary precautions against malware on your devices and networks; and (e) promptly notifying us if you discover or otherwise suspect any security breaches related to your wallet. Notwithstanding anything to the contrary herein, we shall have no liability whatsoever in connection with activities that occur on your wallet with or without your authorization.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Transaction Fees</p>
                <p>There may be transaction fees (e.g. mining fees) associated with your virtual currency transactions that are required by the virtual currency system or blockchain network that you engage with. You must ensure that you have an adequate balance in your wallet and/or “gas” to complete transactions before initiating a transaction. You acknowledge and agree that we will not be liable for any failed transactions or losses you incur due to incorrectly set transaction fees (i.e. too low or too high) or due to insufficient funds or gas associated with your wallet address. You further acknowledge and agree that we do not have access to your or anyone else’s transactions.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Your Use of Wealth Assets</p>
                <p>You agree that you will not violate any laws when using our Services. This includes any local, provincial, state, federal, national, or international laws that may apply to you. You agree that you will not use our Services to pay for, support, or otherwise engage in any illegal activities including, but not limited to, illegal or otherwise prohibited trade, illegal gambling, fraud, money laundering, or terrorist activities. For the avoidance of doubt, if we discover that you have violated these Terms and/or any applicable laws or regulatory requirements, including, but not limited to, the Bank Secrecy Act, we reserve all of our rights and remedies under these Terms and at law and will take all necessary actions against you. You further agree that: (i) you will not encourage or induce any third party to engage in any of the activities prohibited under this Section; (ii) you will not impersonate someone or use or attempt to use another user’s wallet without authorization or use our Services in any manner that could interfere, disrupt, negatively affect, or inhibit other users from fully enjoying it; (iii) you will not distribute any virus or other harmful computer code through wealthassets; (iv) you will not take any action that may impose an unreasonable or disproportionately large load on our or any of our third party providers’ infrastructure; (v) you will not reverse engineer or bypass, circumvent, or attempt to bypass or circumvent any measures that we may use to prevent or restrict access to the Services including, without limitation, other accounts, computer systems, or networks connected to the Services; and (vi) you will not violate, misappropriate or infringe the rights of wealthassets, our users, or others, including privacy, publicity, intellectual property, or other proprietary rights. Although we have no obligation to monitor any user content, we have absolute discretion to take any necessary actions any time and for any reason without notice in the event you breach these Terms. Any use of wealthassets other than as specifically authorized in these Terms, without our prior written permission, is strictly prohibited and we shall have the right to terminate your license to use wealthassets immediately without notice. You acknowledge and accept that by using the Services, you may be exposed to content that is offensive, indecent, or objectionable. We take no responsibility and assume no liability for any user content, including any loss or damage to any of your user content.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Limitation of Liability & Disclaimer of Warranties</p>
                <p>You acknowledge and agree that we have no control over, and no duty to take any action regarding: (i) failures, disruptions, errors, or delays in the processing of Digital Assets that you may experience while using the Services; (ii) the risk of failure of hardware, software, and Internet connections; (iii) the risk of malicious software being introduced or found in the software underlying wealthassets; (iv) the risk that third parties may obtain unauthorized access to information stored within your wallet, including, but not limited to your wallet address, private key, and Secret Phrase; and (v) the risk of unknown vulnerabilities in or unanticipated changes to the the applicable blockchain networks. You release us from all liability related to any losses, damages, or claims arising from: (a) user error such as forgotten passwords, incorrectly constructed transactions, or mistyped Digital Asset addresses; (b) server failure or data loss; (c) unauthorized access to the wealthassets application; (d) bugs or other errors in the wealthassets software; and (e) any unauthorized third party activities, including, but not limited to, the use of viruses, phishing, brute forcing, or other means of attack against wealthassets. We make no representations concerning any Third Party Content contained in or accessed through our Services. Any other terms, conditions, warranties, or representations associated with such content, are solely between you and such organizations and/or individuals.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Indemnity</p>   
                <p>To the extent permitted by applicable law, you agree to defend, indemnify, and hold harmless us, our affiliates, and our respective shareholders, members, directors, officers, employees, attorneys, agents, representatives, suppliers and contractors, from and against any and all claims, damages, obligations, losses, liabilities, tort, costs or debt, and expenses (including, but not limited to, attorney’s fees) arising from: (a) your use of and access to the Services; (b) any feedback or submissions you provide to us concerning wealthassets; (c) violation of any Third Party Content (d) your violation of the Terms; or (e) your violation of any law, rule, or regulation, or the rights of any third party.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">The Limitation on Claims</p> 
                <p>You agree that any claim you may have arising out of or related to your relationship with us must be filed within one year after such claim arises, otherwise, your claim is permanently barred.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Governing Law</p>
                <p>No matter where you’re located, the laws of the State of California will govern these Terms and the parties’ relationship as if you signed these Terms in California, without regard to California’s conflicts of laws rules. If any provisions of these Terms are inconsistent with any applicable law, those provisions will be superseded or modified only to the extent such provisions are inconsistent. The parties agree to submit to the federal or state courts in California for exclusive jurisdiction of any dispute arising out of or related to your use of the Services or your breach of these Terms. You waive any objection based on lack of personal jurisdiction, place of residence, improper venue, or forum non convenient in any such action.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Termination</p> 
                <p>In the event of termination concerning your license to use Wealth Assets, your obligations under this Agreement will still continue. Your access to the funds in your Wallet after termination will depend on your access to your backup of your Wallet address and private key.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Discount of Services</p> 
                <p>We may, in our sole discretion and without cost to you, with or without prior notice, and at any time, modify or discontinue, temporarily or permanently, any portion of our Services. You are solely responsible for storing outside of the Services a backup of any wallet address and private key pair that you maintain in your wallet. Maintaining an external backup of any wallet address and private key pairs associated with your wallet will allow you to access the blockchain network upon which your wallet is secured. Such a backup will allow you to fully restore your wallet at any time without cost or loss of your Digital Assets. If you do not maintain a backup of your wallet data outside of the Services, you will not be able to access the Digital Assets associated with your wallet. wealthassets shall not be held responsible or liable for any loss of Digital Assets in the event that we discontinue all or any part of the Services.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Force Majeure</p> 
                <p>We shall not be held liable for any delays, failure in performance, or interruptions of service which result directly or indirectly from any cause or condition beyond our reasonable control, including but not limited to: any delay or failure due to any acts of God, acts of civil or military authorities, acts of terrorism, civil or industrial disturbances, blockages, embargoes, war, strikes or other labor disputes, fire, earthquakes, storms or other nature-related events, interruption in electrical telecommunications or Internet services or network provider services, failure of hardware equipment and/or software or other utility failures, smart contract bugs or weaknesses, technological changes, changes in interest rates or other monetary conditions, and, for the avoidance of doubt, changes to any blockchain-related protocol, other catastrophe, or any other occurrences which are beyond our reasonable control, and shall not affect the validity and enforceability of any remaining provisions. If we are unable to perform our Services outlined in the Terms due to factors beyond our control, including, but not limited to, the aforementioned force majeure events or changes in applicable laws and/or sanctions policies, we shall not be liable for the Services provided under these Terms during the time period coincident with the event in question.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Entire Agreement</p>
                <p>This Agreement sets forth the entire understanding and agreement as to the subject matter hereof and supersedes any and all prior discussions, agreements, and understandings of any kind (including, without limitation, any prior versions of the Terms) and every nature between us. Except as provided for above, any modification to these Terms must be in writing and must be signed by both parties.</p>
            </div>
            <div className="flex flex-col gap-y-5 mt-10">
                <p className="text-sm md:text-base xl:text-lg font-semibold text-primary">Questions or Comments</p>
                <p>If you have any questions relating to these Terms, your rights and obligations arising from these Terms and/or your use of wealthassets and our Services or any other matter please send us a message on our contact page at info@wealthassets.com</p>
            </div>
        </main>
     );
}
 
export default WalletRegistration;